### ISSUE TITLE
Acquia key and secret via environment variable

### ISSUE THREAD

**Issue by shelane** [typhonius/acquia_cli#29]
I would like to add this as part of a docker-based environment where each member of our team has their key and secret stored as an environment variable. We would not want a file containing that information to be placed into the git repository.

Will it read it if the file is set as:
```yml
acquia:
  key: ${SECRET_ACAPI_KEY}
  secret: ${SECRET_ACAPI_SECRET}
```

Or is there another way to accomplish the same thing?
